import { AliasToken, SeedToken } from 'antd/lib/theme/interface';

export const defaultAntdTheme: Partial<AliasToken> | undefined = {
  // Color Tokens
  colorPrimary: '#1890ff',
  colorSuccess: '#52c41a',
  colorWarning: '#faad14',
  colorError: '#f5222d',
  colorInfo: '#13c2c2',
  colorTextBase: '#000000',
  colorBgBase: '#ffffff',
  colorLink: '#1890ff',

  // Font Tokens
  fontFamily: "'Helvetica Neue', Arial, sans-serif",
  fontFamilyCode: "'Courier New', monospace",
  fontSize: 14,
  lineWidth: 1,
  lineType: 'solid',
  borderRadius: 4,
  sizeUnit: 4,
  sizeStep: 4,
  sizePopupArrow: 6,
  controlHeight: 32,
  zIndexBase: 10,
  zIndexPopupBase: 1000,
  opacityImage: 0.8,
  motionUnit: 100,
  motionBase: 200,
  motionEaseOutCirc: 'cubic-bezier(0.25, 1, 0.5, 1)',
  motionEaseInOutCirc: 'cubic-bezier(0.68, -0.55, 0.27, 1.55)',
  motionEaseInOut: 'cubic-bezier(0.42, 0, 0.58, 1)',
  motionEaseOutBack: 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
  motionEaseInBack: 'cubic-bezier(0.68, -0.55, 0.27, 1.55)',
  motionEaseInQuint: 'cubic-bezier(0.755, 0.05, 0.855, 0.06)',
  motionEaseOutQuint: 'cubic-bezier(0.23, 1, 0.32, 1)',
  motionEaseOut: 'cubic-bezier(0.215, 0.61, 0.355, 1)',

  wireframe: false,
  motion: true,

  // Color Neutral Tokens
  colorText: '#333333',
  colorTextSecondary: '#666666',
  colorTextTertiary: '#999999',
  colorTextQuaternary: '#cccccc',
  colorBorder: '#d9d9d9',
  colorBorderSecondary: '#f0f0f0',
  colorFill: '#f5f5f5',
  colorFillSecondary: '#fafafa',
  colorFillTertiary: '#f0f0f0',
  colorFillQuaternary: '#e6e6e6',
  colorBgLayout: '#f0f2f5',
  colorBgContainer: '#ffffff',
  colorBgElevated: '#ffffff',
  colorBgSpotlight: '#e6f7ff',
  colorBgBlur: '#f7f7f7',
  colorBgSolid: '#ffffff',
  colorBgSolidActive: '#d9d9d9',
  colorBgSolidHover: '#f0f0f0',

  // Color Primary Tokens
  colorPrimaryBg: '#e6f7ff',
  colorPrimaryBgHover: '#bae7ff',
  colorPrimaryBorder: '#91d5ff',
  colorPrimaryBorderHover: '#40a9ff',
  colorPrimaryHover: '#40a9ff',
  colorPrimaryActive: '#096dd9',
  colorPrimaryTextHover: '#ffffff',
  colorPrimaryText: '#ffffff',
  colorPrimaryTextActive: '#ffffff',

  // Color Success Tokens
  colorSuccessBg: '#f6ffed',
  colorSuccessBgHover: '#b7eb8f',
  colorSuccessBorder: '#95de64',
  colorSuccessBorderHover: '#73d13d',
  colorSuccessHover: '#52c41a',
  colorSuccessActive: '#389e0d',
  colorSuccessTextHover: '#ffffff',
  colorSuccessText: '#ffffff',
  colorSuccessTextActive: '#ffffff',

  // Color Warning Tokens
  colorWarningBg: '#fff7e6',
  colorWarningBgHover: '#ffe58f',
  colorWarningBorder: '#ffc53d',
  colorWarningBorderHover: '#faad14',
  colorWarningHover: '#faad14',
  colorWarningActive: '#d48806',
  colorWarningTextHover: '#ffffff',
  colorWarningText: '#ffffff',
  colorWarningTextActive: '#ffffff',

  // Color Info Tokens
  colorInfoBg: '#e6f7ff',
  colorInfoBgHover: '#91d5ff',
  colorInfoBorder: '#69c0ff',
  colorInfoBorderHover: '#40a9ff',
  colorInfoHover: '#13c2c2',
  colorInfoActive: '#08979c',
  colorInfoTextHover: '#ffffff',
  colorInfoText: '#ffffff',
  colorInfoTextActive: '#ffffff',

  // Color Error Tokens
  colorErrorBg: '#fff1f0',
  colorErrorBgHover: '#ffccc7',
  colorErrorBgFilledHover: '#ff7a45',
  colorErrorBgActive: '#f5222d',
  colorErrorBorder: '#ff4d4f',
  colorErrorBorderHover: '#f5222d',
  colorErrorHover: '#f5222d',
  colorErrorActive: '#d62a2a',
  colorErrorTextHover: '#ffffff',
  colorErrorText: '#ffffff',
  colorErrorTextActive: '#ffffff',

  // Color Link Tokens
  colorLinkHover: '#40a9ff',
  colorLinkActive: '#096dd9',

  // Alias Tokens
  colorFillContentHover: '#f0f0f0',
  colorFillAlter: '#fafafa',
  colorFillContent: '#ffffff',
  colorBgContainerDisabled: '#e6e6e6',
  colorBgTextHover: '#f0f0f0',
  colorBgTextActive: '#f5f5f5',
  colorBorderBg: '#d9d9d9',
  colorSplit: '#f0f0f0',
  colorTextPlaceholder: '#d9d9d9',
  colorTextDisabled: '#bfbfbf',
  colorTextHeading: '#000000',
  colorTextLabel: '#666666',
  colorTextDescription: '#999999',
  colorTextLightSolid: '#f5f5f5',
  colorIcon: '#000000',
  colorIconHover: '#1890ff',
  colorHighlight: '#f0f0f0',
  controlOutline: '#1890ff',
  colorWarningOutline: '#faad14',
  colorErrorOutline: '#f5222d',
  fontSizeIcon: 16,
  fontWeightStrong: 700,
  controlOutlineWidth: 2,
  controlItemBgHover: '#f0f0f0',
  controlItemBgActive: '#d9d9d9',
  controlItemBgActiveHover: '#e6e6e6',
  controlInteractiveSize: 32,
  controlItemBgActiveDisabled: '#f5f5f5',
  lineWidthFocus: 2,

  // Padding & Margin Tokens
  paddingXXS: 4,
  paddingXS: 8,
  paddingSM: 12,
  padding: 16,
  paddingMD: 20,
  paddingLG: 24,
  paddingXL: 32,
  paddingContentHorizontalLG: 40,
  paddingContentHorizontal: 32,
  paddingContentHorizontalSM: 24,
  paddingContentVerticalLG: 48,
  paddingContentVertical: 40,
  paddingContentVerticalSM: 32,
  marginXXS: 4,
  marginXS: 8,
  marginSM: 12,
  margin: 16,
  marginMD: 20,
  marginLG: 24,
  marginXL: 32,
  marginXXL: 40,
  opacityLoading: 0.3,
  boxShadow: '0 2px 8px rgba(0, 0, 0, 0.15)',
  boxShadowSecondary: '0 4px 16px rgba(0, 0, 0, 0.15)',
  boxShadowTertiary: '0 8px 32px rgba(0, 0, 0, 0.15)',
  linkDecoration: 'none',
  linkHoverDecoration: 'underline',
  linkFocusDecoration: 'underline',
  controlPaddingHorizontal: 16,
  controlPaddingHorizontalSM: 12,
  screenXS: 320,
  screenXSMin: 320,
  screenXSMax: 480,
  screenSM: 768,
  screenSMMin: 768,
  screenSMMax: 1024,
  screenMD: 1280,
  screenMDMin: 1280,
  screenMDMax: 1600,
  screenLG: 1920,
  screenLGMin: 1920,
  screenXL: 2560,
  screenXLMin: 2560,
};
